IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2205, host_ip: "127.0.0.1"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8805, host_ip: "127.0.0.1"
    ubuntu.vm.network "private_network", ip: "192.168.1.5", virtualbox__intnet: "zabbix"
    ubuntu.vm.hostname = "hostzbx"
  end

  config.vm.provision "shell", path: "install.sh"
  config.vm.provision "shell", path: "configure.sh"
end